# Official Tomcat image with Java
FROM tomcat:9.0-jdk11

# Remove default root webapps to avoid conflicts
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy your built WAR file to Tomcat webapps folder as ROOT.war
COPY target/SmartLibrary-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]